# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TourMore' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TourMore
pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'Firebase/Firestore'
pod 'FirebaseFirestoreSwift'
pod 'Firebase/Core'
pod 'Firebase/Database'

end
